using System.Numerics;
using SkiaSharp;
using Tm2Ac.Geometry;

namespace Tm2Ac.AcTrack.Synthetic;

/// <summary>
/// Phase 1 test track: an L-shaped closed circuit built entirely in code, used to verify our KN5/folder output and AC's
/// axis conventions in game. Driven from the start line the corners are: right, right, right, LEFT, right, right.
/// The left wall is blue ("LEFT ▶"), the right wall red ("◀ RIGHT"), and "TM2AC ▲" is painted on the road at the start;
/// every arrow should point in the race direction and all text should read normally.
/// </summary>
public static class TestCircuit
{
    public const string TrackId = "tm2ac_test_lcircuit";

    private const float RoadHalfWidth = 6f;
    private const float WallOffset = 16f;
    private const float WallHeight = 1.2f;
    private const float GroundHeight = -0.02f;
    private const float CornerRadius = 35f;
    private const int GridSlots = 8;

    /// <summary>
    /// Corner points in AC metres (x, z). Facing +Z, left is +X (AcAxes), so the first corner at (0, 300) turns right toward −X.
    /// Leg lengths: 300 north, 250 west, 150 south, 100 east, 150 south, 150 east.
    /// </summary>
    private static readonly Vector2[] Corners =
    [
        new(0, 0), new(0, 300), new(-250, 300), new(-250, 150), new(-150, 150), new(-150, 0),
    ];

    public static AcTrackModel Build()
    {
        var line = Centerline.RoundedPolygon(Corners, CornerRadius, step: 2f);
        var startDistance = line.NearestDistance(new Vector3(0, 0, 150));

        var track = new AcTrackModel
        {
            Id = TrackId,
            MapPath = line,
            Ui = new UiTrackInfo("Tm2Ac Test Circuit (L)")
            {
                Description = "Synthetic Phase 1 test track generated by Tm2Ac. Corners from the start: right, right, right, LEFT, right, right. "
                    + "Blue LEFT wall should be on your left, red RIGHT wall on your right, and all arrows should point forward.",
                Tags = ["tm2ac", "test", "circuit"],
                Country = "Trackmania",
                Author = "Tm2Ac",
                Version = "phase1",
                Url = "https://github.com/costbubbles/TM-track-exporter",
                Run = "clockwise",
            },
        };

        track.Surfaces.Add(StandardSurfaces.Road);
        track.Surfaces.Add(StandardSurfaces.Grass);

        AddTexture(track, "tm2ac_asphalt.png", Asphalt());
        AddTexture(track, "tm2ac_grass.png", Grass());
        AddTexture(track, "tm2ac_wall_left.png", WallTexture("LEFT ▶", new SKColor(0x1F, 0x5F, 0xD6)));
        AddTexture(track, "tm2ac_wall_right.png", WallTexture("◀ RIGHT", new SKColor(0xD3, 0x2F, 0x2F)));
        AddTexture(track, "tm2ac_start.png", StartDecal());

        track.Materials.Add(new AcMaterial("asphalt", "tm2ac_asphalt.png"));
        track.Materials.Add(new AcMaterial("grass", "tm2ac_grass.png") { Specular = 0 });
        track.Materials.Add(new AcMaterial("wall_left", "tm2ac_wall_left.png"));
        track.Materials.Add(new AcMaterial("wall_right", "tm2ac_wall_right.png"));
        track.Materials.Add(new AcMaterial("start_decal", "tm2ac_start.png") { Shader = "ksPerPixelAT", AlphaTested = true });

        // Road: visual + ROAD collision.
        var road = TrackMeshes.Ribbon(line, RoadHalfWidth, -RoadHalfWidth, 0, uAcross: 1, vLength: 12);
        track.VisualMeshes.Add(new AcVisualMesh("road", "asphalt", road) { CastShadows = false });
        track.CollisionMeshes.Add(new AcCollisionMesh(SurfaceKeys.Road, road));

        // Ground: grass everywhere, slightly below the road.
        var (min, max) = (new Vector3(line.Points.Min(p => p.X), 0, line.Points.Min(p => p.Z)), new Vector3(line.Points.Max(p => p.X), 0, line.Points.Max(p => p.Z)));
        var ground = TrackMeshes.Ground(min.X - 80, max.X + 80, min.Z - 80, max.Z + 80, GroundHeight, cellSize: 25, uvTile: 8);
        track.VisualMeshes.Add(new AcVisualMesh("ground", "grass", ground) { CastShadows = false });
        track.CollisionMeshes.Add(new AcCollisionMesh(SurfaceKeys.Grass, ground));

        // Walls: blue on the left of the race direction, red on the right.
        var leftWall = TrackMeshes.Wall(line, WallOffset, GroundHeight, WallHeight, uLength: 8, twoSided: true);
        var rightWall = TrackMeshes.Wall(line, -WallOffset, GroundHeight, WallHeight, uLength: 8, twoSided: true);
        track.VisualMeshes.Add(new AcVisualMesh("wall_left", "wall_left", leftWall));
        track.VisualMeshes.Add(new AcVisualMesh("wall_right", "wall_right", rightWall));
        track.CollisionMeshes.Add(new AcCollisionMesh(SurfaceKeys.Wall, leftWall));
        track.CollisionMeshes.Add(new AcCollisionMesh(SurfaceKeys.Wall, rightWall));

        // Start decal: checkered line + "TM2AC ▲" just past the line, visual only.
        var (startPos, startForward) = line.Sample(startDistance);
        track.VisualMeshes.Add(new AcVisualMesh("start_decal", "start_decal", Decal(startPos, startForward, RoadHalfWidth, length: 12)) { CastShadows = false });

        // Timing: start/finish line plus two sector gates.
        track.Dummies.AddRange(AcDummies.Gate(AcNames.TimeGate(0), startPos, startForward, RoadHalfWidth + 1));
        for (var sector = 1; sector <= 2; sector++)
        {
            var (pos, fwd) = line.Sample(startDistance + (line.Length * sector / 3));
            track.Dummies.AddRange(AcDummies.Gate(AcNames.TimeGate(sector), pos, fwd, WallOffset));
        }

        // Staggered grid behind the line; pit boxes share the grid slots (as several community tracks do).
        for (var n = 0; n < GridSlots; n++)
        {
            var (pos, fwd) = line.Sample(startDistance - 8 - (8 * n));
            var lateral = AcAxes.Left(fwd) * (n % 2 == 0 ? 3f : -3f);
            track.Dummies.Add(new AcDummy(AcNames.Start(n), pos + lateral, fwd));
            track.Dummies.Add(new AcDummy(AcNames.Pit(n), pos + lateral, fwd));
        }

        var (hotlapPos, hotlapFwd) = line.Sample(startDistance - 100);
        track.Dummies.Add(new AcDummy(AcNames.HotlapStart, hotlapPos, hotlapFwd));

        return track;
    }

    private static void AddTexture(AcTrackModel track, string name, byte[] png) => track.Textures.Add(new AcTexture(name, png));

    /// <summary>Quad on the road surface starting at the start line, mapped so the texture reads upright for an approaching driver.</summary>
    private static MeshData Decal(Vector3 position, Vector3 forward, float halfWidth, float length)
    {
        var left = AcAxes.Left(forward);
        var lift = new Vector3(0, 0.01f, 0);
        var mesh = new MeshData();

        // v = 0 at the far edge (image top = further ahead), u = 0 on the left (image left = driver's left).
        var nearLeft = mesh.AddVertex(position + (left * halfWidth) + lift, AcAxes.Up, new Vector2(0, 1));
        var nearRight = mesh.AddVertex(position - (left * halfWidth) + lift, AcAxes.Up, new Vector2(1, 1));
        var farRight = mesh.AddVertex(position - (left * halfWidth) + (forward * length) + lift, AcAxes.Up, new Vector2(1, 0));
        var farLeft = mesh.AddVertex(position + (left * halfWidth) + (forward * length) + lift, AcAxes.Up, new Vector2(0, 0));
        mesh.AddQuad(nearLeft, nearRight, farRight, farLeft);
        return mesh;
    }

    private static byte[] Asphalt()
    {
        using var bitmap = new SKBitmap(256, 256);
        using var canvas = new SKCanvas(bitmap);
        canvas.Clear(new SKColor(0x4A, 0x4C, 0x50));
        Noise(canvas, 256, 256, seed: 1, SKColors.Black, SKColors.White, alpha: 18);
        using var paint = new SKPaint { Color = new SKColor(0xEE, 0xEE, 0xEE) };
        canvas.DrawRect(6, 0, 6, 256, paint);       // left edge line
        canvas.DrawRect(244, 0, 6, 256, paint);     // right edge line
        canvas.DrawRect(125, 0, 6, 128, paint);     // dashed centre line
        return Encode(bitmap);
    }

    private static byte[] Grass()
    {
        using var bitmap = new SKBitmap(256, 256);
        using var canvas = new SKCanvas(bitmap);
        canvas.Clear(new SKColor(0x3D, 0x7A, 0x2E));
        Noise(canvas, 256, 256, seed: 2, new SKColor(0x20, 0x50, 0x18), new SKColor(0x7F, 0xB0, 0x50), alpha: 60);
        return Encode(bitmap);
    }

    /// <summary>Wall tile (8 m × 1.2 m): coloured band with the label repeated, white trim at top and bottom.</summary>
    private static byte[] WallTexture(string label, SKColor color)
    {
        using var bitmap = new SKBitmap(512, 128);
        using var canvas = new SKCanvas(bitmap);
        canvas.Clear(color);
        using var trim = new SKPaint { Color = SKColors.White };
        canvas.DrawRect(0, 0, 512, 10, trim);
        canvas.DrawRect(0, 118, 512, 10, trim);
        using var font = new SKFont(ArrowCapableTypeface(), 64) { Embolden = true };
        using var text = new SKPaint { Color = SKColors.White, IsAntialias = true };
        canvas.DrawText(label, 256, 88, SKTextAlign.Center, font, text);
        return Encode(bitmap);
    }

    /// <summary>Checkered start line at the near edge and "TM2AC ▲" ahead of it (image top = further down the road).</summary>
    private static byte[] StartDecal()
    {
        using var bitmap = new SKBitmap(512, 512);
        using var canvas = new SKCanvas(bitmap);
        canvas.Clear(SKColors.Transparent);
        using var black = new SKPaint { Color = SKColors.Black };
        using var white = new SKPaint { Color = SKColors.White };
        const int squares = 16;
        const float size = 512f / squares;
        for (var row = 0; row < 2; row++)
        {
            for (var col = 0; col < squares; col++)
            {
                canvas.DrawRect(col * size, 512 - ((row + 1) * size), size, size, (row + col) % 2 == 0 ? black : white);
            }
        }

        using var font = new SKFont(ArrowCapableTypeface(), 120) { Embolden = true };
        using var text = new SKPaint { Color = new SKColor(0xF2, 0xB1, 0x34), IsAntialias = true };
        canvas.DrawText("▲", 256, 200, SKTextAlign.Center, font, text);
        canvas.DrawText("TM2AC", 256, 360, SKTextAlign.Center, font, text);
        return Encode(bitmap);
    }

    private static SKTypeface ArrowCapableTypeface() =>
        SKFontManager.Default.MatchCharacter('▶') ?? SKTypeface.Default;

    private static void Noise(SKCanvas canvas, int width, int height, int seed, SKColor dark, SKColor light, byte alpha)
    {
        var random = new Random(seed);
        using var paint = new SKPaint();
        for (var i = 0; i < width * height / 4; i++)
        {
            paint.Color = (random.Next(2) == 0 ? dark : light).WithAlpha(alpha);
            canvas.DrawRect(random.Next(width), random.Next(height), 2, 2, paint);
        }
    }

    private static byte[] Encode(SKBitmap bitmap)
    {
        using var data = bitmap.Encode(SKEncodedImageFormat.Png, 100);
        return data.ToArray();
    }
}
