using System.Globalization;
using System.Numerics;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using Tm2Ac.AcTrack.Ini;
using Tm2Ac.Geometry;
using Tm2Ac.Kn5;

namespace Tm2Ac.AcTrack;

/// <summary>Writes a complete single-layout AC track folder (SPEC §7.1).</summary>
public static class AcTrackWriter
{
    /// <summary>Marker file: folders containing it were written by Tm2Ac and may be overwritten or uninstalled.</summary>
    public const string ReportFileName = "conversion-report.json";

    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    /// <summary>Writes <paramref name="track"/> into <paramref name="trackDirectory"/> (the folder named after the track ID).</summary>
    /// <param name="report">Extra fields for conversion-report.json (source, options, warnings).</param>
    public static void Write(AcTrackModel track, string trackDirectory, JsonObject? report = null)
    {
        ArgumentNullException.ThrowIfNull(track);
        EnsureWritable(trackDirectory);

        Directory.CreateDirectory(trackDirectory);
        var data = Directory.CreateDirectory(Path.Combine(trackDirectory, "data")).FullName;
        var ui = Directory.CreateDirectory(Path.Combine(trackDirectory, "ui")).FullName;

        Kn5Writer.Write(TrackKn5Builder.BuildVisual(track), Path.Combine(trackDirectory, track.Id + ".kn5"));
        Kn5Writer.Write(TrackKn5Builder.BuildCollision(track), Path.Combine(trackDirectory, TrackKn5Builder.CollisionFileName));
        ModelsIni(track.Id).Save(Path.Combine(trackDirectory, "models.ini"));

        SurfacesIni.Build(track.Surfaces, track.ExtendedPhysics).Save(Path.Combine(data, "surfaces.ini"));
        LightingIni(track.Lighting).Save(Path.Combine(data, "lighting.ini"));
        GrooveIni().Save(Path.Combine(data, "groove.ini"));
        CamerasIni(track).Save(Path.Combine(data, "cameras.ini"));

        if (track.AiLine is { Count: > 1 } aiLine)
        {
            var aiDirectory = Directory.CreateDirectory(Path.Combine(trackDirectory, "ai")).FullName;
            FastLaneAi.Write(aiLine, Path.Combine(aiDirectory, "fast_lane.ai"));
        }

        var layout = MapLayout.FromPath(track.MapPath.Points);
        layout.ToIni().Save(Path.Combine(data, "map.ini"));
        File.WriteAllBytes(Path.Combine(trackDirectory, "map.png"), MapImages.RenderMap(track.MapPath, layout));
        File.WriteAllBytes(Path.Combine(ui, "outline.png"), MapImages.RenderOutline(track.MapPath));
        File.WriteAllBytes(Path.Combine(ui, "preview.png"), track.PreviewPng ?? MapImages.RenderPreview(track.MapPath, track.Ui.Name));
        File.WriteAllText(Path.Combine(ui, "ui_track.json"), UiTrackJson(track).ToJsonString(JsonOptions));

        File.WriteAllText(Path.Combine(trackDirectory, "README_TM2AC.txt"),
            "Generated by Tm2Ac (https://github.com/costbubbles/TM-track-exporter).\r\n" +
            "Tracks converted from Trackmania contain assets extracted from your own Trackmania install.\r\n" +
            "They are for personal use only. Do not redistribute them.\r\n");

        var fullReport = report ?? [];
        fullReport["generator"] = "Tm2Ac";
        fullReport["trackId"] = track.Id;
        fullReport["writtenAtUtc"] = DateTime.UtcNow.ToString("O", CultureInfo.InvariantCulture);
        File.WriteAllText(Path.Combine(trackDirectory, ReportFileName), fullReport.ToJsonString(JsonOptions));
    }

    /// <summary>Throws if the folder exists, is not empty and was not written by Tm2Ac.</summary>
    public static void EnsureWritable(string trackDirectory)
    {
        if (Directory.Exists(trackDirectory)
            && Directory.EnumerateFileSystemEntries(trackDirectory).Any()
            && !File.Exists(Path.Combine(trackDirectory, ReportFileName)))
        {
            throw new IOException($"'{trackDirectory}' already exists and was not created by Tm2Ac; refusing to overwrite it.");
        }
    }

    private static IniFile ModelsIni(string trackId)
    {
        var ini = new IniFile();
        string[] files = [trackId + ".kn5", TrackKn5Builder.CollisionFileName];
        for (var i = 0; i < files.Length; i++)
        {
            ini.Section($"MODEL_{i}").Set("FILE", files[i]).Set("POSITION", "0,0,0").Set("ROTATION", "0,0,0");
        }

        return ini;
    }

    private static IniFile LightingIni(LightingSettings lighting)
    {
        var ini = new IniFile();
        ini.Section("LIGHTING").Set("SUN_PITCH_ANGLE", lighting.SunPitchAngle).Set("SUN_HEADING_ANGLE", lighting.SunHeadingAngle);
        return ini;
    }

    /// <summary>Same groove setup as Kunos tracks (e.g. magione).</summary>
    private static IniFile GrooveIni()
    {
        var ini = new IniFile();
        ini.Section("HEADER").Set("GROOVES_NUMBER", 3);
        ini.Section("GROOVE_0").Set("NAME", "groove").Set("MIN", 0.4f).Set("MAX", 1.1f).Set("MULT", 5);
        ini.Section("GROOVE_1").Set("NAME", "groove2").Set("MIN", 0).Set("MAX", 1).Set("MULT", 1);
        ini.Section("GROOVE_2").Set("NAME", "groove3").Set("MIN", 0).Set("MAX", 1).Set("MULT", 5);
        return ini;
    }

    /// <summary>One fixed TV camera overlooking the first grid slot, covering the whole lap (keys copied from Kunos cameras.ini).</summary>
    private static IniFile CamerasIni(AcTrackModel track)
    {
        var start = track.Dummies.FirstOrDefault(d => d.Name == AcNames.Start(0)) ?? new AcDummy("", Vector3.Zero, Vector3.UnitZ);
        var forward = Vector3.Normalize(new Vector3(start.Forward.X, 0, start.Forward.Z));
        var position = start.Position + (AcAxes.Left(forward) * 25) + (Vector3.UnitY * 12) + (forward * 30);
        var look = Vector3.Normalize(start.Position - position);
        var up = Vector3.Normalize(Vector3.Cross(look, Vector3.Cross(Vector3.UnitY, look)));

        var ini = new IniFile();
        ini.Section("HEADER").Set("VERSION", 3).Set("CAMERA_COUNT", 1).Set("SET_NAME", "TV 1");
        ini.Section("CAMERA_0")
            .Set("NAME", "start")
            .Set("POSITION", position)
            .Set("FORWARD", look)
            .Set("UP", up)
            .Set("MIN_FOV", 10).Set("MAX_FOV", 50)
            .Set("IN_POINT", 0).Set("OUT_POINT", 1)
            .Set("SHADOW_SPLIT0", 50).Set("SHADOW_SPLIT1", 100).Set("SHADOW_SPLIT2", 350)
            .Set("NEAR_PLANE", 1).Set("FAR_PLANE", 35000)
            .Set("MIN_EXPOSURE", 0.2f).Set("MAX_EXPOSURE", 0.45f)
            .Set("DOF_FACTOR", 1).Set("DOF_RANGE", 250).Set("DOF_FOCUS", 20).Set("DOF_MANUAL", 0)
            .Set("SPLINE", "").Set("SPLINE_ROTATION", 0).Set("FOV_GAMMA", 0.5f).Set("SPLINE_ANIMATION_LENGTH", 10)
            .Set("IS_FIXED", 0);
        return ini;
    }

    /// <summary>ui_track.json. Kunos stores numbers as strings, so we do too.</summary>
    private static JsonObject UiTrackJson(AcTrackModel track)
    {
        var ui = track.Ui;
        var json = new JsonObject
        {
            ["name"] = ui.Name,
            ["description"] = ui.Description,
            ["tags"] = new JsonArray(ui.Tags.Select(t => (JsonNode?)JsonValue.Create(t)).ToArray()),
            ["geotags"] = new JsonArray(),
            ["country"] = ui.Country,
            ["city"] = ui.City,
            ["length"] = MathF.Round(track.MapPath.Length).ToString(CultureInfo.InvariantCulture),
            ["pitboxes"] = track.Dummies.Count(d => d.Name.StartsWith("AC_PIT_", StringComparison.Ordinal)).ToString(CultureInfo.InvariantCulture),
            ["run"] = ui.Run,
            ["author"] = ui.Author,
            ["version"] = ui.Version,
            ["url"] = ui.Url,
        };

        if (ui.Year is { } year)
        {
            json["year"] = year;
        }

        return json;
    }
}
